[257,253] Remove WatchOptions as no longer needed
arkmq-org/arkmq-org-broker-operator pull request #262
Opened 2022-07-05 08:57 UTC by gaohoward

2022-07-05 09:36 UTC, gtully commented on controllers/activemqartemis_controller.go
> +	reqLogger.Info("Reconciling ActiveMQArtemis", request.Name, request.Namespace)
maybe remove this, the Reconciling is already in the line above as a nv pair

2022-07-05 10:05 UTC, gtully requested changes
Just to clarify... the reconcilers used to have a flag/list of namespaces and filtered events on reconcile.
now the controller has a list of namespaces and the event cache is filtered at source? Events not in a matching namespace never reach the reconcilers now.

2022-07-05 10:22 UTC, gaohoward commented on controllers/activemqartemisaddress_controller.go
> +	reqLogger.Info("Reconciling ActiveMQArtemisAddress")
+1, yes I didn't notice the information is added to the logger already.

2022-07-05 10:22 UTC, gaohoward commented on controllers/suite_test.go
> +		logf.Log.Info("##### Set up manager to watch multiple namespaces #####")
+1

2022-07-05 10:22 UTC, gaohoward commented on main.go
>  		watchNameSpace = ""
+1

2022-07-05 16:58 UTC, gtully approved these changes

2022-07-06 04:35 UTC, gaohoward commented
> 

Yes I think that's expected. However I don't expect the event behavior to be changed after we remove the WatchOptions. This is because since we upgraded to the new operator-sdk, both cache and WatchOptions have been used and the WatchOptions is duplicate (which means the *match* call inside a reconciler always returns true). Are there any specific events we are missing?

2022-07-06 05:32 UTC, merged