[#910] Remove Scaledown CRD
arkmq-org/arkmq-org-broker-operator pull request #911
Opened 2024-04-29 03:30 UTC by gaohoward

2024-04-29 05:02 UTC, brusdev requested changes
Great cleanup!

The only blocker is a release that includes https://github.com/artemiscloud/activemq-artemis-operator/commit/d7babc9a1ee8f56dec66a6fb591298b3a8829921

2024-04-30 03:46 UTC, gaohoward commented on controllers/activemqartemisscaledown_controller.go
> +type ActiveMQArtemisMessageMigrationControl struct {
yeah it should be renamed. Good catch!

2024-04-30 09:35 UTC, gaohoward commented on controllers/activemqartemisscaledown_controller.go
> +type ActiveMQArtemisMessageMigrationControl struct {
changed it to draft. It's a major change we should try not be included in minor releases.

2025-01-02 09:29 UTC, brusdev commented
This project is now part of the ArkMQ initiative. This repository has been archived as all activities are now happening in the [corresponding ArkMQ repository](https://github.com/arkmq-org/activemq-artemis-operator). See [here](https://artemiscloud.io/community/transition/) for the ArkMQ transition details.

2025-01-02 09:29 UTC, closed without merging